
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 3d0ae71)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GUION = 15;
  public static final int PUNTO = 11;
  public static final int DOSPT = 13;
  public static final int CADENA = 19;
  public static final int LETRA = 17;
  public static final int DECIMAL = 18;
  public static final int ERROR = 22;
  public static final int BARRA = 10;
  public static final int MAYORQUE = 7;
  public static final int PORCENTAJE = 3;
  public static final int LLAVEIZQ = 8;
  public static final int COMA = 12;
  public static final int LLAVEDER = 9;
  public static final int EOF = 0;
  public static final int ASTERISCO = 4;
  public static final int SIMBOLO = 21;
  public static final int CONJ = 16;
  public static final int error = 1;
  public static final int PREGUNTA = 5;
  public static final int ENTERO = 20;
  public static final int SYM_ENIE = 6;
  public static final int MAS = 2;
  public static final int PTCOMA = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "PORCENTAJE",
  "ASTERISCO",
  "PREGUNTA",
  "SYM_ENIE",
  "MAYORQUE",
  "LLAVEIZQ",
  "LLAVEDER",
  "BARRA",
  "PUNTO",
  "COMA",
  "DOSPT",
  "PTCOMA",
  "GUION",
  "CONJ",
  "LETRA",
  "DECIMAL",
  "CADENA",
  "ENTERO",
  "SIMBOLO",
  "ERROR"
  };
}

